### ISSUE TITLE
Revisar el proyecto anterior y sus modelos

### ISSUE THREAD

**Issue by grumysh** [udistrital/movilidad_academica_mid#11]
Analizar el proyecto anterior presentado al CERI para tomar la decisión de continuar el proyecto o de comenzar uno nuevo.

Documentación  asociada:

1. **Repositorio**: https://github.com/udistrital/ceri 

2.  **Modelo de datos**: 
![Modelo Relacional](https://user-images.githubusercontent.com/29903400/58340934-ab4d6d00-7e12-11e9-9fdd-d48c86f89605.jpg)
3. **Mockups**:
[ceri.zip](https://github.com/udistrital/movilidad_academica_mid/files/3217696/ceri.zip)
4. **Servicios**: 

- Generar servicio para obtener datos de los docentes:
  _Entrada_: Número de identificación.
  _Salida_: Nombres, Apellidos, Facultad, Dirección, Teléfono, país de procedencia.

- Generar servicio para obtener datos de los estudiantes:
   _Entrada_: Número de identificación.
   _Salida_: Nombres, Apellidos, Clasificación del programa académico, Programa académico, Facultad,   Dirección, Teléfono, país de procedencia.

- Listado de dependencias de la universidad

- Listado de IES, instituciones o empresas

- Listado de paises

**Comment by grumysh** [comment]
Despues del analisís individual y grupal de la documentación y recursos se decidió iniciar un nuevo proyecto. Se procedió a plantear la Arquitectura y el modelo de Base de datos.

- Arquitectura: 
![MovilidadCeri](https://user-images.githubusercontent.com/43799065/58212309-f8ff9380-7cb3-11e9-98b9-d5cc9c3ec259.png)

- Modelo de Datos: 
![modelo de bd del ceri](https://user-images.githubusercontent.com/29903400/58199883-16723480-7c97-11e9-839e-c30e600df408.png)

**Comment by BOTOOM** [comment]
## motivos de cambio de la base de datos.
en el análisis grupal se ha decidido no usar la base de datos que estaba propuesta del proyecto anterior ya que su modelo no es optimo, no es bueno cargar una tabla con todas la relaciones.

Adicionalmente a ello se tiene en cuenta que a la fecha ya se han creado servicios que podemos integrar. Teniendo encenta esos factores se planteo un nuevo modelo de la base de datos.

## motivos de cambio en el uso del cliente.

el cliente ya realizado en angular en el anterior proyecto ha se ha decidido no usarse y realizar uno nuevo, este con ayuda del generador de [ngx-generator](https://github.com/BOTOOM/ngxGenerator) ya que este ya tiene implementado el uso de WSO2, y en sus actualizaciones recientes ya contempla el uso de reducers, servicios centralizados y fácil modificación para extender el proyecto a futuros cambios.

**Comment by Soulfilip-UD** [comment]
Se reviso el anterior proyectos, se decidio empezar con un nuevo modelo y un nuevo cliente. Se documento y se da el Issue por finalizado
