### ISSUE TITLE
Funcion Get Movilidad para el crud

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/movilidad_academica_mid#13]
Se debe realizar la función GET entre el mid y el crud desarrolado en #9:  

- [x] La función debe traer toda la información del modelo establecido.
- [x] Realizar prueba del endpoint todo traiga todo el modelo de movilidad
- [ ]  La función debe traer la información con un Id particular
- [x] Realizar prueba del endpoint todo traiga  el modelo de movilidad por id

**Calidad**
- [x]  La función cumple con los lineamientos de la oficina
- [x]  La función realiza la funcionalidad esperada

**Comment by Soulfilip-UD** [comment]
Issue finalizado!
