### ISSUE TITLE
Funcion Get persona entre  mid y cliente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/movilidad_academica_mid#15]
Se debe realizar la funcion get para obtener la información requerida de perosna entre el mid y el cliente, esto hace parte de la issues #9

**Comment by ManuelMurillo** [comment]
Votacion Poker: 3 horas

**Comment by BOTOOM** [comment]
no se uso el utils de la organización udistrital, se uso otro método diferente ya que la petición al mid causaba problemas

tomo mas tiempo del esperado.

**Comment by Soulfilip-UD** [comment]
Issue con nuevos requermientos, se finaliza este
