### ISSUE TITLE
Funcion Get para Obtener Convenios

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/movilidad_academica_mid#16]
crear función y endpoint que permita retornar el json ya creado en el Issue #8

**Comment by BOTOOM** [comment]
se configura endpoint para obtener el json de convenios del issue #8 .

este json se puede obtener mediante el path `http://localhost:8081/v1/convenio/GetConvenio`

**Comment by Soulfilip-UD** [comment]
Cambios en producción , Issue finalizado
