### ISSUE TITLE
modificar arquitectura

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/movilidad_academica_mid#28]
Se debe modificar la  arquitectura del proyecto segun los requerimientos establecidos en le sprint 1:

- [x] Diseñar la arquitectura con archi.

**Calidad**
- [x] La arquitectura cumple con los lineamientos de la OAS

**Comment by ManuelMurillo** [comment]
Votacion Poker planning 2 Horas

**Comment by fabianbarreto02** [comment]
![Version2](https://user-images.githubusercontent.com/43799065/58650044-49d64400-82d3-11e9-9b7e-ca955a4ea69c.png)

**Comment by fabianbarreto02** [comment]
[Version2.archimate.zip](https://github.com/udistrital/movilidad_academica_mid/files/3237984/Version2.archimate.zip)

**Comment by Soulfilip-UD** [comment]
Tarea finalizada, requiere modificaciones pero se adjuntan a un nuevo Issue
