### ISSUE TITLE
Ajustar Readme de MID

### ISSUE THREAD

**Issue by grumysh** [udistrital/movilidad_academica_mid#3]
Ajustar readme de repositorio teniendo en cuenta los lineamientos de la oficina: https://github.com/udistrital/introduccion_oas/blob/master/repositorios_institucionales/contenido_readme.md

**Comment by BOTOOM** [comment]
se designan 4 horas para realizarce

**Comment by Soulfilip-UD** [comment]
La documentación es clara, requerira unas modificaciones pero se adjuntaran a un nuevo Issue, Issue finalizado!
