### ISSUE TITLE
Relizar json que simule los datos que se solicitan de la API Academica

### ISSUE THREAD

**Issue by grumysh** [udistrital/movilidad_academica_mid#5]
Relizar json para simular los datos que se necesitan de API Academica.

**Comment by fabianbarreto02** [comment]
En baso a los datos suministrados por el servicio de academia determinar que datos son relevantes son relevantes para la aplicación

**Comment by BOTOOM** [comment]
se define 1 hora segun poker planning

**Comment by Soulfilip-UD** [comment]
Se realizaron las prubas con el json efectivamente. Issue finalizado!
