### ISSUE TITLE
json para convenios o organizaciones

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/movilidad_academica_mid#8]
realizar un json de prueba quemado en el mid. 

este Json debe contener los datos ideales que se esperarían del servicio que permita traer las organizaciones, con el fin de poder realizar pruebas antes de conseguir acceso y/o uso de los servicios.

**Comment by BOTOOM** [comment]
se definen una hora para realizarce

**Comment by Soulfilip-UD** [comment]
Datosútilas, pruebas satisfactoria. Issue finalizado se procede a cerrarlo
